app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000
  database-access-type: jooq

spring:
  application:
    name: scrapper
  datasource:
    url: unset
    username: unset
    password: unset
    driver-class-name: unset
  jooq:
    sql-dialect: postgres

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

clients:
  bot:
    base-url: unset
  github:
    base-url: unset
  stack-overflow:
    base-url: unset

authorization-tokens:
  github: unset
