app:
  telegram-token: unset
  retry:
    max-attempts: 3
    exceptions:
      - java.lang.RuntimeException
      - java.net.SocketException
    backoff:
      delay: 1000
      max-delay: 5000
      multiplier: 1

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=3600s
    cache-names:
      - rate-limit-bucket

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

clients:
  scrapper:
    base-url: unset

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-bucket
      url: .*
      http-status-code: too_many_requests
      rate-limits:
        - bandwidths:
            - capacity: 10
              time: 1
              unit: minutes
              refill-speed: interval
          cache-key: getRemoteAddr()
          skip-condition: '@bucket4jWhiteListService.isWhiteList(getRemoteAddr())'

clients-whitelist: unset
