/*
 * This file is generated by jOOQ.
 */

package edu.java.dao.jooq_generated;

import edu.java.dao.jooq_generated.tables.Chat;
import edu.java.dao.jooq_generated.tables.ChatLinkAssociation;
import edu.java.dao.jooq_generated.tables.Link;
import edu.java.dao.jooq_generated.tables.records.ChatLinkAssociationRecord;
import edu.java.dao.jooq_generated.tables.records.ChatRecord;
import edu.java.dao.jooq_generated.tables.records.LinkRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CHAT_PKEY =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("chat_pkey"), new TableField[] {Chat.CHAT.ID}, true);
    public static final UniqueKey<ChatLinkAssociationRecord> CHAT_LINK_ASSOCIATION_PKEY = Internal.createUniqueKey(
        ChatLinkAssociation.CHAT_LINK_ASSOCIATION,
        DSL.name("chat_link_association_pkey"),
        new TableField[] {ChatLinkAssociation.CHAT_LINK_ASSOCIATION.LINK_ID,
            ChatLinkAssociation.CHAT_LINK_ASSOCIATION.CHAT_ID},
        true
    );
    public static final UniqueKey<LinkRecord> LINK_PKEY =
        Internal.createUniqueKey(Link.LINK, DSL.name("link_pkey"), new TableField[] {Link.LINK.ID}, true);
    public static final UniqueKey<LinkRecord> LINK_RESOURCE_KEY =
        Internal.createUniqueKey(Link.LINK, DSL.name("link_resource_key"), new TableField[] {Link.LINK.RESOURCE}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatLinkAssociationRecord, ChatRecord>
        CHAT_LINK_ASSOCIATION__CHAT_LINK_ASSOCIATION_CHAT_ID_FKEY =
        Internal.createForeignKey(
            ChatLinkAssociation.CHAT_LINK_ASSOCIATION,
            DSL.name("chat_link_association_chat_id_fkey"),
            new TableField[] {ChatLinkAssociation.CHAT_LINK_ASSOCIATION.CHAT_ID},
            Keys.CHAT_PKEY,
            new TableField[] {Chat.CHAT.ID},
            true
        );
    public static final ForeignKey<ChatLinkAssociationRecord, LinkRecord>
        CHAT_LINK_ASSOCIATION__CHAT_LINK_ASSOCIATION_LINK_ID_FKEY =
        Internal.createForeignKey(
            ChatLinkAssociation.CHAT_LINK_ASSOCIATION,
            DSL.name("chat_link_association_link_id_fkey"),
            new TableField[] {ChatLinkAssociation.CHAT_LINK_ASSOCIATION.LINK_ID},
            Keys.LINK_PKEY,
            new TableField[] {Link.LINK.ID},
            true
        );
}
