/*
 * This file is generated by jOOQ.
 */

package edu.java.dao.jooq_generated;

import edu.java.dao.jooq_generated.tables.Chat;
import edu.java.dao.jooq_generated.tables.ChatLinkAssociation;
import edu.java.dao.jooq_generated.tables.Link;
import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>public.chat</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>public.chat_link_association</code>.
     */
    public static final ChatLinkAssociation CHAT_LINK_ASSOCIATION = ChatLinkAssociation.CHAT_LINK_ASSOCIATION;

    /**
     * The table <code>public.link</code>.
     */
    public static final Link LINK = Link.LINK;
}
