/*
 * This file is generated by jOOQ.
 */

package edu.java.dao.jooq_generated.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Link implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String resource;
    private LocalDateTime updatedAt;

    public Link() {
    }

    public Link(Link value) {
        this.id = value.id;
        this.resource = value.resource;
        this.updatedAt = value.updatedAt;
    }

    @ConstructorProperties({"id", "resource", "updatedAt"})
    public Link(
        @Nullable Long id,
        @NotNull String resource,
        @Nullable LocalDateTime updatedAt
    ) {
        this.id = id;
        this.resource = resource;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.link.id</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.link.id</code>.
     */
    public void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.link.resource</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public String getResource() {
        return this.resource;
    }

    /**
     * Setter for <code>public.link.resource</code>.
     */
    public void setResource(@NotNull String resource) {
        this.resource = resource;
    }

    /**
     * Getter for <code>public.link.updated_at</code>.
     */
    @Nullable
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.link.updated_at</code>.
     */
    public void setUpdatedAt(@Nullable LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Link other = (Link) obj;
        if (this.id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!this.id.equals(other.id)) {
            return false;
        }
        if (this.resource == null) {
            if (other.resource != null) {
                return false;
            }
        } else if (!this.resource.equals(other.resource)) {
            return false;
        }
        if (this.updatedAt == null) {
            if (other.updatedAt != null) {
                return false;
            }
        } else if (!this.updatedAt.equals(other.updatedAt)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.resource == null) ? 0 : this.resource.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Link (");

        sb.append(id);
        sb.append(", ").append(resource);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
