/*
 * This file is generated by jOOQ.
 */

package edu.java.dao.jooq_generated.tables.records;

import edu.java.dao.jooq_generated.tables.pojos.ChatLinkAssociation;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ChatLinkAssociationRecord extends UpdatableRecordImpl<ChatLinkAssociationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chat_link_association.link_id</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chat_link_association.link_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.chat_link_association.chat_id</code>.
     */
    public void setChatId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chat_link_association.chat_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatLinkAssociationRecord
     */
    public ChatLinkAssociationRecord() {
        super(edu.java.dao.jooq_generated.tables.ChatLinkAssociation.CHAT_LINK_ASSOCIATION);
    }

    /**
     * Create a detached, initialised ChatLinkAssociationRecord
     */
    @ConstructorProperties({"linkId", "chatId"})
    public ChatLinkAssociationRecord(@NotNull Long linkId, @NotNull Long chatId) {
        super(edu.java.dao.jooq_generated.tables.ChatLinkAssociation.CHAT_LINK_ASSOCIATION);

        setLinkId(linkId);
        setChatId(chatId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ChatLinkAssociationRecord
     */
    public ChatLinkAssociationRecord(ChatLinkAssociation value) {
        super(edu.java.dao.jooq_generated.tables.ChatLinkAssociation.CHAT_LINK_ASSOCIATION);

        if (value != null) {
            setLinkId(value.getLinkId());
            setChatId(value.getChatId());
            resetChangedOnNotNull();
        }
    }
}
